name: Continuous Delivery

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: 'dev.continuous-deploy.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy occurring at development environment
  
  homolog:
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: 'homolog.continuous-deploy.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy occurring at homolog environment
  
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'continuous-deploy.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy occurring at production environment
